//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, v2.3.2 
// See <a href="https://javaee.github.io/jaxb-v2/">https://javaee.github.io/jaxb-v2/</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2020.05.07 at 03:25:43 PM EDT 
//


package com.javaspringdemo.employees;

import javax.xml.bind.annotation.XmlRegistry;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the com.javaspringdemo.employees package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {


    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: com.javaspringdemo.employees
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link GetEmployeeDetailsReq }
     * 
     */
    public GetEmployeeDetailsReq createGetEmployeeDetailsReq() {
        return new GetEmployeeDetailsReq();
    }

    /**
     * Create an instance of {@link GetEmployeeDetailsResponse }
     * 
     */
    public GetEmployeeDetailsResponse createGetEmployeeDetailsResponse() {
        return new GetEmployeeDetailsResponse();
    }

    /**
     * Create an instance of {@link EmployeeDetails }
     * 
     */
    public EmployeeDetails createEmployeeDetails() {
        return new EmployeeDetails();
    }

    /**
     * Create an instance of {@link GetAllEmployeeDetailsReq }
     * 
     */
    public GetAllEmployeeDetailsReq createGetAllEmployeeDetailsReq() {
        return new GetAllEmployeeDetailsReq();
    }

    /**
     * Create an instance of {@link GetAllEmployeeDetailsResponse }
     * 
     */
    public GetAllEmployeeDetailsResponse createGetAllEmployeeDetailsResponse() {
        return new GetAllEmployeeDetailsResponse();
    }

}
